<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="DESKTOP-U08CU62" name="com.crxmarkets.dev.qa2.loginpagetests.LoginTests" tests="2" failures="1" timestamp="18 мая 2020 07:57:05 GMT" time="25.947" errors="0">
  <testcase name="PositiveLoginTest" time="12.162" classname="com.crxmarkets.dev.qa2.loginpagetests.LoginTests">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	Severe error: chrome-extension://nejjhhjbbdlbnpfhbclcilanmofmgdlk/index.html 0:0 Uncaught SyntaxError: Unexpected token &lt; in JSON at position 0">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
Severe error: chrome-extension://nejjhhjbbdlbnpfhbclcilanmofmgdlk/index.html 0:0 Uncaught SyntaxError: Unexpected token < in JSON at position 0
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
at com.crxmarkets.dev.qa2.loginpagetests.LoginTests.PositiveLoginTest(LoginTests.java:55)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- PositiveLoginTest -->
  <testcase name="PositiveLoginTest" time="13.785" classname="com.crxmarkets.dev.qa2.loginpagetests.LoginTests"/>
</testsuite> <!-- com.crxmarkets.dev.qa2.loginpagetests.LoginTests -->
